### PR TITLE
Bump to support intl-tel-input < Number.MAX_SAFE_INTEGER

### PR DESCRIPTION
**Pull request by tlebreton**
Hi :)

This pr allow us to use intl-tel-input 20 [Changelog](https://github.com/jackocnr/intl-tel-input/releases/tag/v20.0.0)

I needed to update test unit because of this :

> Remove defaultToFirstCountry option as that behaviour was https://github.com/jackocnr/intl-tel-input/issues/1525#issuecomment-1957751527 and so is not recommended (you can always use initialCountry to set the initial country if you wish to)

I decide to add` initialCountry: "ch"` because it solve test but don't know if it's correct or not.

Another thinks that changes is the way validNumber works : 

> By default, calling isValidNumber will now default to mobile-only mode (it will only return true for valid mobile numbers), which means it will be https://github.com/jackocnr/intl-tel-input/issues/1535 - if you don't want this, you can pass false as an argument e.g. isValidNumber(false)

It can be solved with another options 'isMobileVerification' with default to true(like intl-tel-input)

What is your opinion on this subject ?

### CODE REVIEW

**Comment by mpalourdio** [comment]
Wow, another upstream breaking update, so cool (no).

I suggest we wait for one week or two. The last version (19) has had lots of releases in its short life days. And from what I see, this one has already 4 updates since yersterday :D

**Comment by tlebreton** [comment]
Yeah i fully understand you :D 

Please leaves it open and in the begin of april i will be back to you.

**Comment by jackocnr** [comment]
uh oh, you guys are really going to hate me now 😂

**Comment by mpalourdio** [comment]
@jackocnr @tlebreton whe shoud `"intl-tel-input":">20.0.0"` in package.json, WDYT ? :smiling_face_with_tear:

**Comment by mpalourdio** [comment]
I have update the PR title accordingly :laughing:

**Comment by tlebreton** [comment]
I will take the time by the end of the week to update the pr according to change made by @jackocnr

**Pull request closed without merging**
